### ISSUE TITLE
New Player intro

### ISSUE THREAD

**Issue by GnarlyOldGuy** [andrewminer/ad-astra#3]
Hello, my name is David B, and I have been toying around with the mod pack on a standalone. 

I think I would like to try the server, looks challenging and interesting.

Rules
Be nice to others, treat them like you would want to be treated.
Don't start any fights or battles, unless you ask first.  But why do that? We are all here to have fun, right?
Leave other people's stuff alone, refer to rule one for clarification.
Don't build your stuff close to others, it's a big world, and there are only a few of us here.
Label your stuff when you make it, they may want to be amazed by your creative style and grace.
Don't dig big unsightly holes in the ground just because you can.  Have some regard for the environment even though it's not real.

My UID is GnarlyOldGuy.  I'm old and pretty much a noob at Minecraft, so this should be interesting.

**Comment by andrewminer** [comment]
You should be all set to log in!
